server:
 port: 8080

spring:
  profiles: dev
---
server:
 port: 8081

spring:
 profiles: test
---
server:
 port: 8082

spring:
 profiles: pro
---
spring:
  profiles:
    active: pro


mybatis:
#  config-location: 指定mybatis核心配置文件
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cawl.mybatis.domain

